feat: optional static domain for callback & allow setting statecookie.domain
sevensolutions/traefik-oidc-auth pull request #30
Opened 2024-12-30 05:10 UTC by cdanis

* Make configurable a static domain (+scheme) when computing the callback URL
* Make configurable the StateCookie's domain name

This allows a particularly useful combination when you're running many apps in subdomains of yourdomain.com:
* Set the cookie's Domain to yourdomain.com
* Use auth.yourdomain.com as your fixed callback URL

This lets you use the same middleware to wrap many different backend services, but shares the cookie between all apps, and also means you only have to register a single callback URL in your IDP.

2024-12-30 16:02 UTC, cdanis commented
BTW: I've tested this locally in a few scenarios and it seems to work.  I'll soon add docs as well, but wanted to quickly get eyes on the draft PR in case of any issues.

2024-12-31 15:00 UTC, sevensolutions commented
Thank you for this PR @cdanis 👍.

I think i know what you're trying to achieve but shouldn't this be handled by SSO of the IDP itself?
Eg.: You navigate to `service1.mydomain.com`. You get redirected to the IDP and login. You get a cookie for this sub-domain.
Then you navigate to `service2.mydomain.com`. You also get redirected to the IDP but it knows you're already logged in and you get redirected to service2 immediately.

So: Do you want to get rid of this "unnecessary" redirect?

Let me play around a bit with your code...

2025-01-01 03:13 UTC, cdanis commented
> Thank you for this PR @cdanis 👍.
> 
> I think i know what you're trying to achieve but shouldn't this be handled by SSO of the IDP itself? Eg.: You navigate to `service1.mydomain.com`. You get redirected to the IDP and login. You get a cookie for this sub-domain. Then you navigate to `service2.mydomain.com`. You also get redirected to the IDP but it knows you're already logged in and you get redirected to service2 immediately.

Really, the critical thing for this use case is the static callback URI.  It's a huge convenience if you are spinning up new services often.

Currently I'm using [thomseddon/traefik-forward-auth's "Auth Host Mode"](https://github.com/thomseddon/traefik-forward-auth#auth-host-mode) but I'm looking for a replacement.  Avoiding ForwardAuth entirely by using a plugin seems like it'd be great :grinning: 

The cookie domain is indeed just an optimization, but I think a worthwhile one.  (Both [thomseddon/traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth?tab=readme-ov-file#option-details) and [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#cookie-options) support custom cookie domains and document the auth-on-a-subdomain case.)


> 
> Let me play around a bit with your code...
> 
> EDIT: Do you please have a config example for me? What i'am trying:
> _[...]_
> 
> But it looks i'am still getting the cookies attached to the wrong domain, resulting in a login-redirect-loop.

Ah, I think you're getting bit by the cookie domain not having any dots in it at all, which the browser will [reject](https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain).

Instead of using .localhost you could use:

127.0.0.1.[sslip.io](https://sslip.io)
auth.127.0.0.1.sslip.io
service1.127.0.0.1.sslip.io

> What i'am also thinking: Maybe we can combine `CallbackDomain` and `CallbackScheme` into the `CallbackUri` and simply allow absolute `CallbackUri`s`? What do you think? In this case it's the user's responsibility to configure an appropriate route so that the callback is routed back to the plugin.

I think that would be fine.  I almost did that originally, but I got worried it might be confusing to users that only some of the 'Uri' fields in the configuration could be absolute.  Maybe we just need to document it well.

2025-01-01 09:44 UTC, sevensolutions commented
Thank you @cdanis. I always forget about sslip but i got it working.
It's important to use HTTPS btw for the cookies to work correctly.

I think this is a great improvement to the plugin. Thank you so much 👍 

So in my opinion whats missing:
- Combining the CallbackUrl into a single config parameter
- Adding some documentation to the website (Maybe with a real-world example)

> I was also thinking it might be nice to refactor statecookie creation to a helper function, as right now there's both a lot of repetition but also significant-but-subtle differences in the various codepaths. But I erred on the side of sending a minimal PR.

Yes i know the code needs some refactoring which i'am doing from time to time, but this is my first real project using Go and currently, i don't have any Integration Tests.. I think i should add a few tests in the near future..

2025-01-01 15:10 UTC, cdanis commented
> Thank you @cdanis. I always forget about sslip but i got it working. It's important to use HTTPS btw for the cookies to work correctly.

Ah yes sorry, I hacked around this in my own configuration (which didn't use sslip, but instead used manual `/etc/hosts` entries plus my existing homelab).  You can see it in the main branch of my fork: https://github.com/cdanis/traefik-oidc-auth/blob/main/http.yml

> 
> I think this is a great improvement to the plugin. Thank you so much 👍
> 
> So in my opinion whats missing:
> 
>     * Combining the CallbackUrl into a single config parameter
> 
>     * Adding some documentation to the website (Maybe with a real-world example)
> 
>     * The Domain setting for the `CodeVerifier`-cookie seems to be missing, to make PKCE working

All sounds good and will do!

Ah yes and I didn't actually test with PKCE yet -- will do so.


> > I was also thinking it might be nice to refactor statecookie creation to a helper function, as right now there's both a lot of repetition but also significant-but-subtle differences in the various codepaths. But I erred on the side of sending a minimal PR.
> 
> Yes i know the code needs some refactoring which i'am doing from time to time, but this is my first real project using Go and currently, i don't have any Integration Tests.. I think i should add a few tests in the near future..

No worries, I was thinking about doing some of that myself.  Do you know of any really simple IDP that has a decent admin API? Might be nice for writing Dockerized integration tests.

2025-01-01 21:32 UTC, cdanis commented
* [x] single config parameter CallbackUri
* [x] CodeVerifier cookie fixed in the basic case
* [x] Tested w/ PKCE on pocket-id

Still to do:
* [ ] Write documentation
* [ ] Document that the PKCE mode is currently not working with hosts other than the centralized auth host.  This is because we can't set a cross-domain cookie -- we'd need to do a double redirect in this case.

2025-01-02 16:20 UTC, sevensolutions commented
Thx for all the effort you put into this  ❤️

> No worries, I was thinking about doing some of that myself. Do you know of any really simple IDP that has a decent admin API? Might be nice for writing Dockerized integration tests.

Hmm.. no not really.. ZITADEL has a good Admin API but no direct CLI. So we need to use plain HTTP requests..
And running ZITADEL in Docker is very simple. I will play around with that a bit...

2025-01-02 16:37 UTC, cdanis commented
> Thx for all the effort you put into this ❤️

Thanks! It's been fun and has been scratching a longtime personal itch :smile:

My day job is starting back up so I'll have a little less time, but I for sure want to see this PR through.

> Hmm.. no not really.. ZITADEL has a good Admin API but no direct CLI. So we need to use plain HTTP requests.. And running ZITADEL in Docker is very simple. I will play around with that a bit...

Since asking about this, I came across [Dex](https://github.com/dexidp/dex), which allows [statically-defined user accounts and passwords](https://dexidp.io/docs/connectors/local/), supports a [gRPC API](https://dexidp.io/docs/configuration/api/) for admin configuration, and also looks very easy to run inside Docker with either in-memory or sqlite state storage. So that might be another option.

2025-01-02 18:40 UTC, sevensolutions commented
Thank you for the hint about Dex. I've never heard about it but it looks ideal for this use-case.
I've started to play around here a bit: https://github.com/sevensolutions/traefik-oidc-auth/tree/feature/e2e-tests

2025-01-04 22:25 UTC, cdanis commented
PTAL :grinning:

2025-01-04 22:27 UTC, cdanis commented
Whoa, very cool to see the e2e tests run in Actions!  I'd be happy to try adding an e2e test for this in a followup MR.

2025-01-05 08:38 UTC, sevensolutions commented
Thank you @cdanis, i'll have a look at this.

> Whoa, very cool to see the e2e tests run in Actions! I'd be happy to try adding an e2e test for this in a followup MR.

Thank you, this would be very great. But yes, please do this in a separate PR, so we can keep this one small.

2025-01-05 09:59 UTC, sevensolutions requested changes
Thank you @cdanis.
I've tested the code and it works great. Only PKCE isn't working, but it's documented and we have the open issue. Thank you for that.
I've just a few comments about naming to make the code easier to understand.
Can you please have a look on them?
I would then be happy to accept this PR 😀.

2025-01-05 09:59 UTC, sevensolutions commented on main.go
> +func (toa *TraefikOidcAuth) CallbackURLAbsolute(req *http.Request) *url.URL {
Can you please name this "GetAbsoluteCallbackURL"?

2025-01-05 09:59 UTC, sevensolutions commented on main.go
> +func (toa *TraefikOidcAuth) isReqForCallback(req *http.Request) bool {
... and this one "isCallbackRequest"?

2025-01-05 09:59 UTC, sevensolutions commented on main.go
> +func (toa *TraefikOidcAuth) stateCookieTemplate() *http.Cookie {
Maybe "createStateCookie" or "createStateCookieTemplate"?

2025-01-05 09:59 UTC, sevensolutions commented on website/docs/getting-started/callback-uri.md
> +Warning: **absolute callback URLs are incompatible with PKCE**.  See [GH-42](https://github.com/sevensolutions/traefik-oidc-auth/issues/42).
Maybe we should use a *Warning*-[Admonition](https://docusaurus.io/docs/markdown-features/admonitions) here.

2025-01-05 09:59 UTC, sevensolutions commented on website/docs/getting-started/callback-uri.md
> +```yml
Maybe it would be a good idea to provide a full example here.
Like this maybe?

```yml
http:
  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:80

  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          LogLevel: DEBUG
          Provider:
            UrlEnv: "PROVIDER_URL"
            ClientIdEnv: "CLIENT_ID"
            ClientSecretEnv: "CLIENT_SECRET"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]
          CallbackUri: "https://auth.127.0.0.1.sslip.io/oidc/callback"
          StateCookie:
            Domain: ".127.0.0.1.sslip.io"

  routers:
    service1:
      entryPoints: ["websecure"]
      tls: {}
      rule: "Host(`service1.127.0.0.1.sslip.io`)"
      service: whoami
      middlewares: ["oidc-auth@file"]
    service2:
      entryPoints: ["websecure"]
      tls: {}
      rule: "Host(`service2.127.0.0.1.sslip.io`)"
      service: whoami
      middlewares: ["oidc-auth@file"]
    auth:
      entryPoints: ["websecure"]
      tls: {}
      rule: "Host(`auth.127.0.0.1.sslip.io`)"
      service: noop@internal
      middlewares: ["oidc-auth@file"]
```

2025-01-05 10:07 UTC, cdanis commented on website/docs/getting-started/callback-uri.md
> +```yml
Sure! I do think there's value in also providing the much shorter pseudo-production example, so I've included both.

2025-01-05 10:35 UTC, sevensolutions approved these changes

2025-01-05 10:36 UTC, merged